import { drizzle } from "drizzle-orm/node-postgres";
import { Pool } from "pg";
import { bossesTable } from "./schema/bosses.js";

const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const db = drizzle(pool);

const bosses = [
  // ─── WORLD BOSSES ───────────────────────────────────────────────────────────
  {
    name: "Kaguya Otsutsuki",
    title: "The Progenitor of Chakra",
    animeSource: "Naruto",
    element1: "Space" as const,
    element2: "Time" as const,
    tier: "world",
    hp: 500000,
    atk: 3500,
    def: 2000,
    spd: 300,
    crit: 0.25,
    critDmg: 2.5,
    phases: [
      { threshold: 0.75, name: "Infinite Tsukuyomi", atkMultiplier: 1.2, defMultiplier: 1.1, spdMultiplier: 1.0, mechanic: "AoE sleep debuff", specialMove: { name: "Infinite Tsukuyomi", description: "Traps all fighters in a dream world", damage: 1.4, effect: "sleep" } },
      { threshold: 0.40, name: "Rabbit Goddess Form", atkMultiplier: 1.5, defMultiplier: 1.3, spdMultiplier: 1.2, mechanic: "Bone spikes pierce defense", specialMove: { name: "Expansive Truth-Seeking Ball", description: "Obliterates everything in its path", damage: 2.0, effect: "defense_break" } },
    ],
    weaknesses: ["Lightning", "Order"],
    resistances: ["Space", "Time", "Dark"],
    immunities: ["Ice"],
    skills: [
      { name: "Ash Bones", description: "Fires a bone that disintegrates on contact", damage: 1.6, energyCost: 30, cooldown: 2, effect: "instant_kill_chance" },
      { name: "Dimension Shift", description: "Warps to another dimension to dodge", damage: 1.0, energyCost: 20, cooldown: 3, effect: "evasion" },
      { name: "All-Killing Ash Bones", description: "Multi-directional bone barrage", damage: 2.2, energyCost: 50, cooldown: 4 },
    ],
    passive: "Godly Resilience: Reduces all incoming damage by 20%",
    lootTable: [
      { itemType: "summon_ticket", itemName: "Kaguya Fragment Ticket", chance: 0.05, quantity: 1 },
      { itemType: "material", itemName: "Chakra Fruit Essence", chance: 0.3, quantity: 3 },
      { itemType: "currency", itemName: "Gold", chance: 1.0, quantity: 5000 },
    ],
    xpReward: 50000,
    goldReward: 10000,
    isWorldBoss: true,
    isAbyssBoss: false,
    isEnabled: true,
  },
  {
    name: "Yhwach",
    title: "The Almighty — Father of the Quincy",
    animeSource: "Bleach",
    element1: "Light" as const,
    element2: "Dark" as const,
    tier: "world",
    hp: 600000,
    atk: 4000,
    def: 2200,
    spd: 280,
    crit: 0.30,
    critDmg: 2.8,
    phases: [
      { threshold: 0.70, name: "Auswählen", atkMultiplier: 1.3, defMultiplier: 1.0, spdMultiplier: 1.1, mechanic: "Steals power from allies", specialMove: { name: "Auswählen", description: "Drains life force from allies", damage: 1.3, effect: "life_steal" } },
      { threshold: 0.35, name: "The Almighty Activated", atkMultiplier: 1.8, defMultiplier: 1.5, spdMultiplier: 1.5, mechanic: "Can see and alter future", specialMove: { name: "Reality Rewrite", description: "Rewrites the outcome of battle", damage: 2.5, effect: "negate_damage" } },
    ],
    weaknesses: ["Dark", "Chaos"],
    resistances: ["Light", "Order"],
    immunities: ["Time"],
    skills: [
      { name: "Blut Vene Anhaben", description: "Transfers his blood into the enemy", damage: 1.5, energyCost: 25, cooldown: 2 },
      { name: "Sankt Altar", description: "Fires beams of condensed Reishi", damage: 2.0, energyCost: 45, cooldown: 3 },
      { name: "Schrift — The Almighty", description: "Activates complete future sight", damage: 1.8, energyCost: 60, cooldown: 5, effect: "counter_all" },
    ],
    passive: "The Almighty: 15% chance to negate any attack completely",
    lootTable: [
      { itemType: "summon_ticket", itemName: "Quincy Holy Ticket", chance: 0.04, quantity: 1 },
      { itemType: "material", itemName: "Reishi Crystal", chance: 0.35, quantity: 4 },
      { itemType: "currency", itemName: "Gold", chance: 1.0, quantity: 6000 },
    ],
    xpReward: 60000,
    goldReward: 12000,
    isWorldBoss: true,
    isAbyssBoss: false,
    isEnabled: true,
  },
  {
    name: "Rimuru Tempest (True Demon Lord)",
    title: "Ruler of the Jura Tempest Federation",
    animeSource: "Tensura",
    element1: "Water" as const,
    element2: "Chaos" as const,
    tier: "world",
    hp: 450000,
    atk: 3200,
    def: 1900,
    spd: 350,
    crit: 0.28,
    critDmg: 2.3,
    phases: [
      { threshold: 0.65, name: "Harvest Lord Shub-Niggurath", atkMultiplier: 1.25, defMultiplier: 1.15, spdMultiplier: 1.3, mechanic: "Devours enemy skills", specialMove: { name: "Merciless", description: "An unstoppable existence — ignores all resistances", damage: 1.8, effect: "resistance_ignore" } },
      { threshold: 0.30, name: "Infinite Regeneration", atkMultiplier: 1.5, defMultiplier: 2.0, spdMultiplier: 1.5, mechanic: "Heals 5% HP each round", specialMove: { name: "Ultrasonic Black Thunder", description: "Lightning fast annihilation blast", damage: 2.4 } },
    ],
    weaknesses: ["Order", "Space"],
    resistances: ["Water", "Wind", "Earth"],
    immunities: ["Chaos"],
    skills: [
      { name: "Predator", description: "Absorbs enemy attacks and adds them to its own", damage: 1.4, energyCost: 20, cooldown: 2, effect: "absorb" },
      { name: "Storm of Destruction", description: "Summons a catastrophic magical storm", damage: 1.9, energyCost: 40, cooldown: 3 },
      { name: "Megiddo", description: "Concentrates sunlight into a devastating beam", damage: 2.6, energyCost: 55, cooldown: 5 },
    ],
    passive: "Great Sage: Analyzes enemy patterns, +10% damage per round",
    lootTable: [
      { itemType: "summon_ticket", itemName: "Slime Lord Ticket", chance: 0.06, quantity: 1 },
      { itemType: "material", itemName: "Magicule Crystal", chance: 0.4, quantity: 3 },
      { itemType: "currency", itemName: "Gold", chance: 1.0, quantity: 4500 },
    ],
    xpReward: 45000,
    goldReward: 9000,
    isWorldBoss: true,
    isAbyssBoss: false,
    isEnabled: true,
  },
  {
    name: "Sukuna (20 Fingers)",
    title: "King of Curses",
    animeSource: "Jujutsu Kaisen",
    element1: "Dark" as const,
    element2: "Fire" as const,
    tier: "world",
    hp: 550000,
    atk: 3800,
    def: 1800,
    spd: 320,
    crit: 0.35,
    critDmg: 3.0,
    phases: [
      { threshold: 0.60, name: "Malevolent Shrine", atkMultiplier: 1.4, defMultiplier: 1.1, spdMultiplier: 1.2, mechanic: "Domain expansion unleashed", specialMove: { name: "Malevolent Shrine", description: "Opens domain expansion — slashes everything within range", damage: 2.0, effect: "aoe_bleed" } },
      { threshold: 0.25, name: "Cleave + Dismantle Barrage", atkMultiplier: 2.0, defMultiplier: 0.9, spdMultiplier: 1.6, mechanic: "Unstoppable slash barrage", specialMove: { name: "Wither", description: "Decays the target's existence", damage: 3.0, effect: "max_hp_reduce" } },
    ],
    weaknesses: ["Light", "Order"],
    resistances: ["Dark", "Fire", "Chaos"],
    immunities: [],
    skills: [
      { name: "Cleave", description: "Slashes through any defense", damage: 1.7, energyCost: 20, cooldown: 1 },
      { name: "Dismantle", description: "An aerial slash that deals fixed damage", damage: 1.5, energyCost: 15, cooldown: 1 },
      { name: "Reversed Cursed Technique", description: "Heals Sukuna using positive energy", damage: 0.5, energyCost: 35, cooldown: 4, effect: "self_heal" },
    ],
    passive: "King of Curses: All attacks ignore 30% of defense",
    lootTable: [
      { itemType: "summon_ticket", itemName: "Cursed King Ticket", chance: 0.04, quantity: 1 },
      { itemType: "material", itemName: "Cursed Energy Crystal", chance: 0.35, quantity: 4 },
      { itemType: "currency", itemName: "Gold", chance: 1.0, quantity: 5500 },
    ],
    xpReward: 55000,
    goldReward: 11000,
    isWorldBoss: true,
    isAbyssBoss: false,
    isEnabled: true,
  },
  {
    name: "Anos Voldigoad",
    title: "The Demon King of Tyranny",
    animeSource: "The Misfit of Demon King Academy",
    element1: "Dark" as const,
    element2: "Chaos" as const,
    tier: "world",
    hp: 700000,
    atk: 4500,
    def: 2500,
    spd: 260,
    crit: 0.30,
    critDmg: 2.6,
    phases: [
      { threshold: 0.50, name: "Venuzdonoa Unleashed", atkMultiplier: 1.5, defMultiplier: 1.3, spdMultiplier: 1.0, mechanic: "Nullifies all magic", specialMove: { name: "Venuzdonoa", description: "The Sword of Destruction that kills even concepts", damage: 2.5, effect: "magic_negate" } },
      { threshold: 0.20, name: "Demon King Resurrection", atkMultiplier: 2.2, defMultiplier: 2.0, spdMultiplier: 1.4, mechanic: "Revives once at 50% HP", specialMove: { name: "Egil Groene Angdroa", description: "Destroys the very source of magic", damage: 3.5, effect: "source_break" } },
    ],
    weaknesses: ["Order", "Light"],
    resistances: ["Dark", "Chaos", "Fire"],
    immunities: ["Dark"],
    skills: [
      { name: "Demon Eyes of Destruction", description: "Gaze that destroys source of magic", damage: 1.8, energyCost: 25, cooldown: 2, effect: "debuff" },
      { name: "Jio Graze", description: "Fires a condensed magic bullet", damage: 1.6, energyCost: 20, cooldown: 1 },
      { name: "Great Magic Circle Gyze", description: "Summons a world-destroying magic circle", damage: 2.8, energyCost: 60, cooldown: 5 },
    ],
    passive: "Indestructible: Immune to one-shot attacks",
    lootTable: [
      { itemType: "summon_ticket", itemName: "Demon King Ticket", chance: 0.03, quantity: 1 },
      { itemType: "material", itemName: "Source Crystal", chance: 0.25, quantity: 2 },
      { itemType: "currency", itemName: "Gold", chance: 1.0, quantity: 7000 },
    ],
    xpReward: 70000,
    goldReward: 14000,
    isWorldBoss: true,
    isAbyssBoss: false,
    isEnabled: true,
  },

  // ─── ABYSS BOSSES (Floors 10, 20, 30 ... 100) ───────────────────────────────
  {
    name: "Goblin Warlord",
    title: "Chieftain of the Dark Forest",
    animeSource: "Goblin Slayer",
    element1: "Earth" as const,
    element2: "Dark" as const,
    tier: "abyss",
    hp: 5000,
    atk: 300,
    def: 180,
    spd: 90,
    crit: 0.10,
    critDmg: 1.7,
    phases: [
      { threshold: 0.50, name: "Berserk Mode", atkMultiplier: 1.5, defMultiplier: 0.8, spdMultiplier: 1.2, mechanic: "Enrages and attacks twice", specialMove: { name: "Warchief Slam", description: "A devastating ground slam", damage: 1.8 } },
    ],
    weaknesses: ["Fire", "Light"],
    resistances: ["Earth"],
    immunities: [],
    skills: [
      { name: "Pack Assault", description: "Calls goblin allies to swarm the target", damage: 1.4, energyCost: 20, cooldown: 2 },
      { name: "Poison Blade", description: "A venomous strike that deals poison damage", damage: 1.2, energyCost: 15, cooldown: 2, effect: "poison" },
    ],
    passive: "Mob Tactics: +5% ATK for each round survived",
    lootTable: [
      { itemType: "material", itemName: "Goblin Tusk", chance: 0.8, quantity: 2 },
      { itemType: "currency", itemName: "Gold", chance: 1.0, quantity: 500 },
    ],
    xpReward: 1000,
    goldReward: 500,
    isWorldBoss: false,
    isAbyssBoss: true,
    abyssFloor: 10,
    isEnabled: true,
  },
  {
    name: "Grimmjow Jaegerjaquez",
    title: "6th Espada — Pantera",
    animeSource: "Bleach",
    element1: "Wind" as const,
    element2: "Dark" as const,
    tier: "abyss",
    hp: 18000,
    atk: 600,
    def: 350,
    spd: 200,
    crit: 0.18,
    critDmg: 1.9,
    phases: [
      { threshold: 0.45, name: "Resurrección: Pantera", atkMultiplier: 1.6, defMultiplier: 1.2, spdMultiplier: 1.5, mechanic: "Full hollow power unleashed", specialMove: { name: "Desgarrón", description: "Claw attack that shreds through anything", damage: 2.2 } },
    ],
    weaknesses: ["Lightning", "Order"],
    resistances: ["Wind", "Dark"],
    immunities: [],
    skills: [
      { name: "Cero", description: "A powerful energy blast", damage: 1.5, energyCost: 25, cooldown: 2 },
      { name: "Gran Rey Cero", description: "An enhanced royal Cero attack", damage: 2.0, energyCost: 40, cooldown: 3 },
    ],
    passive: "Espada Aggression: Crits deal additional 10% bonus damage",
    lootTable: [
      { itemType: "material", itemName: "Hollow Mask Fragment", chance: 0.5, quantity: 2 },
      { itemType: "currency", itemName: "Gold", chance: 1.0, quantity: 1500 },
    ],
    xpReward: 4000,
    goldReward: 1500,
    isWorldBoss: false,
    isAbyssBoss: true,
    abyssFloor: 20,
    isEnabled: true,
  },
  {
    name: "Garou (Awakened)",
    title: "Hero Hunter — Monster",
    animeSource: "One Punch Man",
    element1: "Earth" as const,
    element2: "Wind" as const,
    tier: "abyss",
    hp: 40000,
    atk: 950,
    def: 600,
    spd: 250,
    crit: 0.20,
    critDmg: 2.0,
    phases: [
      { threshold: 0.40, name: "Cosmic Fear Mode", atkMultiplier: 1.7, defMultiplier: 1.4, spdMultiplier: 1.6, mechanic: "Copies last attack used against him", specialMove: { name: "Flowing Water Crushing Rock Fist", description: "Unblockable martial arts technique", damage: 2.5, effect: "unblockable" } },
    ],
    weaknesses: ["Light", "Order"],
    resistances: ["Earth", "Wind"],
    immunities: [],
    skills: [
      { name: "Whirlwind Iron Cutting Fist", description: "A spinning fist attack that hits multiple times", damage: 1.6, energyCost: 30, cooldown: 2 },
      { name: "Exploding Heart Release Fist", description: "Channels killing intent into a devastating blow", damage: 2.0, energyCost: 45, cooldown: 3 },
    ],
    passive: "Monster Evolution: Gains 5% stats each phase",
    lootTable: [
      { itemType: "material", itemName: "Monster Cell", chance: 0.4, quantity: 2 },
      { itemType: "currency", itemName: "Gold", chance: 1.0, quantity: 3000 },
    ],
    xpReward: 8000,
    goldReward: 3000,
    isWorldBoss: false,
    isAbyssBoss: true,
    abyssFloor: 30,
    isEnabled: true,
  },
  {
    name: "Meruem",
    title: "King of the Chimera Ants",
    animeSource: "Hunter x Hunter",
    element1: "Dark" as const,
    element2: "Lightning" as const,
    tier: "abyss",
    hp: 80000,
    atk: 1400,
    def: 900,
    spd: 280,
    crit: 0.25,
    critDmg: 2.2,
    phases: [
      { threshold: 0.35, name: "Post-Rose Meruem", atkMultiplier: 1.9, defMultiplier: 1.6, spdMultiplier: 1.3, mechanic: "Aura becomes toxic to touch", specialMove: { name: "Nen Infusion", description: "Explosive aura release that damages all nearby", damage: 2.8, effect: "aura_damage" } },
    ],
    weaknesses: ["Light", "Order"],
    resistances: ["Dark", "Lightning"],
    immunities: [],
    skills: [
      { name: "Tail Strike", description: "Whips his tail with crushing force", damage: 1.7, energyCost: 20, cooldown: 1 },
      { name: "Photon", description: "Fires a condensed Nen bolt", damage: 2.0, energyCost: 40, cooldown: 3 },
    ],
    passive: "Absorption: Every kill increases ATK by 3%",
    lootTable: [
      { itemType: "material", itemName: "King's Nen Crystal", chance: 0.35, quantity: 2 },
      { itemType: "currency", itemName: "Gold", chance: 1.0, quantity: 5000 },
    ],
    xpReward: 15000,
    goldReward: 5000,
    isWorldBoss: false,
    isAbyssBoss: true,
    abyssFloor: 40,
    isEnabled: true,
  },
  {
    name: "Madara Uchiha (Ten Tails Jinchuriki)",
    title: "The World's Strongest Shinobi",
    animeSource: "Naruto",
    element1: "Fire" as const,
    element2: "Dark" as const,
    tier: "abyss",
    hp: 150000,
    atk: 2000,
    def: 1200,
    spd: 260,
    crit: 0.28,
    critDmg: 2.3,
    phases: [
      { threshold: 0.50, name: "Limbo: Border Jail", atkMultiplier: 1.4, defMultiplier: 1.3, spdMultiplier: 1.1, mechanic: "Shadow clones fight alongside", specialMove: { name: "Chibaku Tensei", description: "Creates a miniature moon to crush the enemy", damage: 2.3, effect: "gravity_crush" } },
      { threshold: 0.25, name: "Rinne Sharingan", atkMultiplier: 1.8, defMultiplier: 1.5, spdMultiplier: 1.3, mechanic: "Infinite Tsukuyomi casts", specialMove: { name: "Infinite Tsukuyomi", description: "All enemies trapped in the dream world", damage: 1.5, effect: "mass_sleep" } },
    ],
    weaknesses: ["Space", "Time"],
    resistances: ["Fire", "Dark", "Earth"],
    immunities: [],
    skills: [
      { name: "Perfect Susanoo", description: "Summons a colossal armored warrior", damage: 1.9, energyCost: 35, cooldown: 2 },
      { name: "Bijuudama", description: "Fires a concentrated tailed beast bomb", damage: 2.5, energyCost: 55, cooldown: 4 },
    ],
    passive: "Immortal Body: Regenerates 2% HP at start of each round",
    lootTable: [
      { itemType: "material", itemName: "Sharingan Shard", chance: 0.3, quantity: 2 },
      { itemType: "currency", itemName: "Gold", chance: 1.0, quantity: 8000 },
    ],
    xpReward: 25000,
    goldReward: 8000,
    isWorldBoss: false,
    isAbyssBoss: true,
    abyssFloor: 50,
    isEnabled: true,
  },
  {
    name: "Ulquiorra Cifer (Segunda Etapa)",
    title: "4th Espada — Murcielago",
    animeSource: "Bleach",
    element1: "Dark" as const,
    element2: "Wind" as const,
    tier: "abyss",
    hp: 220000,
    atk: 2600,
    def: 1600,
    spd: 310,
    crit: 0.30,
    critDmg: 2.5,
    phases: [
      { threshold: 0.40, name: "Segunda Etapa — True Despair", atkMultiplier: 1.7, defMultiplier: 1.5, spdMultiplier: 1.4, mechanic: "Regenerates heart, becomes immune for 1 round", specialMove: { name: "Lanza del Relámpago", description: "A javelin of Reiatsu that destroys anything it hits", damage: 3.0, effect: "explosion" } },
    ],
    weaknesses: ["Light", "Order"],
    resistances: ["Dark", "Wind"],
    immunities: [],
    skills: [
      { name: "Cero Oscuras", description: "The ultimate Cero of Espada", damage: 2.0, energyCost: 30, cooldown: 2 },
      { name: "Luz de la Luna", description: "A crescent-shaped Reiatsu slash", damage: 1.7, energyCost: 25, cooldown: 2 },
    ],
    passive: "Heart of Nothingness: 20% chance to nullify any attack",
    lootTable: [
      { itemType: "material", itemName: "Espada Hierro Fragment", chance: 0.3, quantity: 2 },
      { itemType: "currency", itemName: "Gold", chance: 1.0, quantity: 10000 },
    ],
    xpReward: 35000,
    goldReward: 10000,
    isWorldBoss: false,
    isAbyssBoss: true,
    abyssFloor: 60,
    isEnabled: true,
  },
  {
    name: "Aizen Sosuke (Hogyoku Fused)",
    title: "The Man Who Stands Atop All",
    animeSource: "Bleach",
    element1: "Light" as const,
    element2: "Dark" as const,
    tier: "abyss",
    hp: 320000,
    atk: 3200,
    def: 2000,
    spd: 290,
    crit: 0.32,
    critDmg: 2.7,
    phases: [
      { threshold: 0.60, name: "First Butterfly Form", atkMultiplier: 1.3, defMultiplier: 1.2, spdMultiplier: 1.1, mechanic: "All attacks become illusions", specialMove: { name: "Kanzen Saimin", description: "Complete hypnosis — causes enemy to attack themselves", damage: 1.5, effect: "confusion" } },
      { threshold: 0.30, name: "Final Cocoon Form", atkMultiplier: 1.8, defMultiplier: 1.7, spdMultiplier: 1.4, mechanic: "Hogyoku grants immortality", specialMove: { name: "Fragor", description: "Fires a massive ball of condensed Reiatsu", damage: 2.8, effect: "all_stats_down" } },
    ],
    weaknesses: ["Chaos", "Order"],
    resistances: ["Light", "Dark"],
    immunities: ["Ice"],
    skills: [
      { name: "Kyoka Suigetsu", description: "Distorts all five senses of the enemy", damage: 1.5, energyCost: 20, cooldown: 2, effect: "all_debuff" },
      { name: "Hado 90: Kurohitsugi", description: "A black coffin of compressed space-time", damage: 2.2, energyCost: 50, cooldown: 4 },
    ],
    passive: "Hogyoku: Negates death once per fight",
    lootTable: [
      { itemType: "material", itemName: "Hogyoku Shard", chance: 0.2, quantity: 1 },
      { itemType: "currency", itemName: "Gold", chance: 1.0, quantity: 14000 },
    ],
    xpReward: 50000,
    goldReward: 14000,
    isWorldBoss: false,
    isAbyssBoss: true,
    abyssFloor: 70,
    isEnabled: true,
  },
  {
    name: "Boros",
    title: "Dominator of the Universe",
    animeSource: "One Punch Man",
    element1: "Lightning" as const,
    element2: "Space" as const,
    tier: "abyss",
    hp: 450000,
    atk: 3800,
    def: 2200,
    spd: 340,
    crit: 0.33,
    critDmg: 2.8,
    phases: [
      { threshold: 0.55, name: "Armored Form Broken", atkMultiplier: 1.4, defMultiplier: 0.9, spdMultiplier: 1.5, mechanic: "Removes armor for massive speed boost", specialMove: { name: "Meteoric Burst", description: "Blasts himself into the enemy at light speed", damage: 2.0 } },
      { threshold: 0.25, name: "Collapsing Star Roaring Cannon", atkMultiplier: 2.0, defMultiplier: 1.2, spdMultiplier: 1.3, mechanic: "Charges for 1 round, then fires", specialMove: { name: "Collapsing Star Roaring Cannon", description: "A planet-busting energy beam", damage: 4.0, effect: "charge" } },
    ],
    weaknesses: ["Dark", "Chaos"],
    resistances: ["Lightning", "Space"],
    immunities: [],
    skills: [
      { name: "Spear of the Far East", description: "Fires an energy spear across the battlefield", damage: 1.8, energyCost: 30, cooldown: 2 },
      { name: "Energy Blade", description: "Creates a sword from condensed energy", damage: 1.6, energyCost: 20, cooldown: 1 },
    ],
    passive: "Regeneration: Recovers 3% HP per round",
    lootTable: [
      { itemType: "material", itemName: "Dark Matter Crystal", chance: 0.25, quantity: 2 },
      { itemType: "currency", itemName: "Gold", chance: 1.0, quantity: 18000 },
    ],
    xpReward: 70000,
    goldReward: 18000,
    isWorldBoss: false,
    isAbyssBoss: true,
    abyssFloor: 80,
    isEnabled: true,
  },
  {
    name: "Isshiki Otsutsuki",
    title: "The Strongest Otsutsuki",
    animeSource: "Boruto",
    element1: "Space" as const,
    element2: "Dark" as const,
    tier: "abyss",
    hp: 600000,
    atk: 4200,
    def: 2500,
    spd: 360,
    crit: 0.35,
    critDmg: 2.9,
    phases: [
      { threshold: 0.50, name: "Sukunahikona Activated", atkMultiplier: 1.5, defMultiplier: 1.3, spdMultiplier: 1.5, mechanic: "Shrinks attacks to avoid damage", specialMove: { name: "Daikokuten", description: "Stores matter in a pocket dimension to summon at will", damage: 2.3, effect: "random_attack" } },
      { threshold: 0.20, name: "Final Assault Mode", atkMultiplier: 2.2, defMultiplier: 1.8, spdMultiplier: 2.0, mechanic: "Hyper-speed rapid strikes", specialMove: { name: "Shrinkage Barrage", description: "Miniaturizes hundreds of rods that expand inside the target", damage: 3.5 } },
    ],
    weaknesses: ["Order", "Time"],
    resistances: ["Space", "Dark"],
    immunities: ["Space"],
    skills: [
      { name: "Kāma", description: "Channels Otsutsuki power through a seal", damage: 1.9, energyCost: 30, cooldown: 2 },
      { name: "Ten-Finger Drilling Bullets", description: "Fires chakra rods that pierce all defenses", damage: 2.1, energyCost: 35, cooldown: 2 },
    ],
    passive: "Otsutsuki Life Force: Cannot be killed instantly; survives at 1 HP once",
    lootTable: [
      { itemType: "material", itemName: "Otsutsuki Kāma Seal", chance: 0.15, quantity: 1 },
      { itemType: "currency", itemName: "Gold", chance: 1.0, quantity: 22000 },
    ],
    xpReward: 90000,
    goldReward: 22000,
    isWorldBoss: false,
    isAbyssBoss: true,
    abyssFloor: 90,
    isEnabled: true,
  },
  // ─── ELITE BOSSES (Mid-tier Challengers) ────────────────────────────────────
  {
    name: "Kisame Hoshigaki",
    title: "Tailless Tailed Beast",
    animeSource: "Naruto",
    element1: "Water" as const,
    element2: "Dark" as const,
    tier: "elite",
    hp: 12000,
    atk: 500,
    def: 320,
    spd: 160,
    crit: 0.15,
    critDmg: 1.8,
    phases: [
      { threshold: 0.50, name: "Samehada Merger", atkMultiplier: 1.5, defMultiplier: 1.2, spdMultiplier: 1.3, mechanic: "Drains enemy chakra each round", specialMove: { name: "Shark Fusion", description: "Merges with Samehada for a devastating bite", damage: 2.1, effect: "chakra_drain" } },
    ],
    weaknesses: ["Lightning", "Fire"],
    resistances: ["Water"],
    immunities: [],
    skills: [
      { name: "Water Prison Jutsu", description: "Traps the enemy in a sphere of water", damage: 1.3, energyCost: 20, cooldown: 2, effect: "immobilize" },
      { name: "Shark Bomb Barrage", description: "Fires explosive water sharks", damage: 1.8, energyCost: 35, cooldown: 3 },
    ],
    passive: "Samehada: Absorbs 10% of all damage dealt to heal Kisame",
    lootTable: [
      { itemType: "material", itemName: "Akatsuki Ring Fragment", chance: 0.4, quantity: 1 },
      { itemType: "currency", itemName: "Gold", chance: 1.0, quantity: 2000 },
    ],
    xpReward: 8000,
    goldReward: 2000,
    isWorldBoss: false,
    isAbyssBoss: false,
    isEnabled: true,
  },
  {
    name: "Toga Himiko",
    title: "Transform Hero Killer",
    animeSource: "My Hero Academia",
    element1: "Dark" as const,
    element2: "Wind" as const,
    tier: "elite",
    hp: 9000,
    atk: 420,
    def: 260,
    spd: 200,
    crit: 0.22,
    critDmg: 1.9,
    phases: [
      { threshold: 0.40, name: "Love Transform", atkMultiplier: 1.6, defMultiplier: 1.0, spdMultiplier: 1.5, mechanic: "Copies enemy's last ability", specialMove: { name: "Blood Copy", description: "Transforms into a powerful copy of the target", damage: 2.0, effect: "copy_skill" } },
    ],
    weaknesses: ["Light", "Fire"],
    resistances: ["Dark", "Wind"],
    immunities: [],
    skills: [
      { name: "Bloody Kiss", description: "Drains blood to fuel transformations", damage: 1.4, energyCost: 15, cooldown: 1, effect: "bleed" },
      { name: "Phantom Transform", description: "Copies and attacks as an ally", damage: 1.7, energyCost: 30, cooldown: 3 },
    ],
    passive: "Obsession: Crits restore 5% HP",
    lootTable: [
      { itemType: "material", itemName: "Quirk Syringe", chance: 0.5, quantity: 1 },
      { itemType: "currency", itemName: "Gold", chance: 1.0, quantity: 1500 },
    ],
    xpReward: 5000,
    goldReward: 1500,
    isWorldBoss: false,
    isAbyssBoss: false,
    isEnabled: true,
  },
  {
    name: "Awakened Ryomen Sukuna (4 Fingers)",
    title: "The Demon of Cursed Techniques",
    animeSource: "Jujutsu Kaisen",
    element1: "Fire" as const,
    element2: "Dark" as const,
    tier: "elite",
    hp: 30000,
    atk: 800,
    def: 500,
    spd: 220,
    crit: 0.25,
    critDmg: 2.2,
    phases: [
      { threshold: 0.45, name: "Open Domain", atkMultiplier: 1.7, defMultiplier: 1.0, spdMultiplier: 1.3, mechanic: "Domain applies slash aura to everything", specialMove: { name: "Open Domain Cleave", description: "Fires invisible slashes in all directions", damage: 2.5, effect: "aoe_slash" } },
    ],
    weaknesses: ["Light", "Order"],
    resistances: ["Dark", "Fire"],
    immunities: [],
    skills: [
      { name: "Cleave", description: "An invisible slash that cuts through all defenses", damage: 1.8, energyCost: 20, cooldown: 1 },
      { name: "Dismantle", description: "Aerial attack that cannot be blocked", damage: 1.6, energyCost: 15, cooldown: 1 },
    ],
    passive: "King's Pride: Immune to fear and debuffs for first 2 rounds",
    lootTable: [
      { itemType: "material", itemName: "Sukuna's Finger Fragment", chance: 0.3, quantity: 1 },
      { itemType: "currency", itemName: "Gold", chance: 1.0, quantity: 3500 },
    ],
    xpReward: 12000,
    goldReward: 3500,
    isWorldBoss: false,
    isAbyssBoss: false,
    isEnabled: true,
  },
  {
    name: "Muzan Kibutsuji (Demon King Form)",
    title: "The Progenitor of All Demons",
    animeSource: "Demon Slayer",
    element1: "Dark" as const,
    element2: "Chaos" as const,
    tier: "elite",
    hp: 45000,
    atk: 1100,
    def: 700,
    spd: 240,
    crit: 0.28,
    critDmg: 2.4,
    phases: [
      { threshold: 0.50, name: "True Demon Form", atkMultiplier: 1.8, defMultiplier: 1.5, spdMultiplier: 1.4, mechanic: "Sprouts multiple arms to attack simultaneously", specialMove: { name: "Cellular Mutation", description: "Reshape his body into an unstoppable weapon", damage: 2.8, effect: "multi_hit" } },
    ],
    weaknesses: ["Light", "Order"],
    resistances: ["Dark", "Chaos"],
    immunities: ["Poison"],
    skills: [
      { name: "Blood Demon Art", description: "Injects blood that corrodes the target", damage: 1.7, energyCost: 25, cooldown: 2, effect: "corrosion" },
      { name: "Regeneration Burst", description: "Regenerates severely damaged tissue", damage: 0.5, energyCost: 40, cooldown: 3, effect: "self_heal" },
    ],
    passive: "Demon King: Cannot be one-shot killed; survives at 1 HP once",
    lootTable: [
      { itemType: "material", itemName: "Muzan Blood Cell", chance: 0.25, quantity: 1 },
      { itemType: "currency", itemName: "Gold", chance: 1.0, quantity: 5000 },
    ],
    xpReward: 18000,
    goldReward: 5000,
    isWorldBoss: false,
    isAbyssBoss: false,
    isEnabled: true,
  },
  {
    name: "Alucard (Hellsing)",
    title: "The King of Vampires",
    animeSource: "Hellsing",
    element1: "Dark" as const,
    element2: "Chaos" as const,
    tier: "elite",
    hp: 55000,
    atk: 1300,
    def: 900,
    spd: 200,
    crit: 0.30,
    critDmg: 2.5,
    phases: [
      { threshold: 0.40, name: "Release Level Zero", atkMultiplier: 2.0, defMultiplier: 1.8, spdMultiplier: 1.2, mechanic: "Summons an army of slain souls", specialMove: { name: "Army of Darkness", description: "Releases millions of devoured souls as weapons", damage: 3.2, effect: "soul_army" } },
    ],
    weaknesses: ["Light", "Order"],
    resistances: ["Dark", "Chaos"],
    immunities: ["Physical"],
    skills: [
      { name: "Jackal Shot", description: "Fires a blessed silver bullet", damage: 2.0, energyCost: 20, cooldown: 1 },
      { name: "Regeneration", description: "Reforms body from shadows", damage: 0.0, energyCost: 30, cooldown: 3, effect: "full_regen_partial" },
    ],
    passive: "Immortal Vampire: Returns from death once per battle with 50% HP",
    lootTable: [
      { itemType: "material", itemName: "Vampire Blood Vial", chance: 0.2, quantity: 1 },
      { itemType: "currency", itemName: "Gold", chance: 1.0, quantity: 6000 },
    ],
    xpReward: 22000,
    goldReward: 6000,
    isWorldBoss: false,
    isAbyssBoss: false,
    isEnabled: true,
  },
  {
    name: "Escanor (Noon)",
    title: "The One Who Stands Above All",
    animeSource: "Seven Deadly Sins",
    element1: "Fire" as const,
    element2: "Light" as const,
    tier: "elite",
    hp: 60000,
    atk: 1500,
    def: 1000,
    spd: 210,
    crit: 0.30,
    critDmg: 2.6,
    phases: [
      { threshold: 0.30, name: "The One — Invincible Noon", atkMultiplier: 2.2, defMultiplier: 2.5, spdMultiplier: 1.0, mechanic: "Becomes completely invincible for 1 round", specialMove: { name: "Divine Axe Rhitta: Cruel Sun", description: "Drops an enormous sun onto the enemy", damage: 3.8, effect: "incinerate" } },
    ],
    weaknesses: ["Water", "Ice"],
    resistances: ["Fire", "Light"],
    immunities: ["Dark"],
    skills: [
      { name: "Sunflare", description: "Fires a focused ray of concentrated sunlight", damage: 2.0, energyCost: 25, cooldown: 2 },
      { name: "Pride", description: "Channel pride to boost all stats", damage: 1.0, energyCost: 20, cooldown: 3, effect: "self_buff" },
    ],
    passive: "Sunshine: ATK scales up 10% per round (max 50%)",
    lootTable: [
      { itemType: "material", itemName: "Sunshine Essence", chance: 0.2, quantity: 1 },
      { itemType: "currency", itemName: "Gold", chance: 1.0, quantity: 7000 },
    ],
    xpReward: 25000,
    goldReward: 7000,
    isWorldBoss: false,
    isAbyssBoss: false,
    isEnabled: true,
  },
  {
    name: "Accelerator (Awakened)",
    title: "Strongest Esper — Level 6",
    animeSource: "A Certain Magical Index",
    element1: "Wind" as const,
    element2: "Chaos" as const,
    tier: "elite",
    hp: 35000,
    atk: 900,
    def: 600,
    spd: 280,
    crit: 0.20,
    critDmg: 2.0,
    phases: [
      { threshold: 0.35, name: "Angel Wings Emerge", atkMultiplier: 1.8, defMultiplier: 1.5, spdMultiplier: 1.6, mechanic: "Reflects 30% of all damage back", specialMove: { name: "Dark Wings", description: "Wings of dark matter annihilate the area", damage: 2.6, effect: "reflect" } },
    ],
    weaknesses: ["Order", "Space"],
    resistances: ["Wind", "Chaos"],
    immunities: [],
    skills: [
      { name: "Vector Reversal", description: "Reflects any projectile attack", damage: 1.5, energyCost: 10, cooldown: 1, effect: "reflect_ranged" },
      { name: "Atmospheric Explosion", description: "Summons plasma from the atmosphere", damage: 2.2, energyCost: 45, cooldown: 4 },
    ],
    passive: "Redirection: Nullifies any attack below 500 base damage",
    lootTable: [
      { itemType: "material", itemName: "Esper Electrode", chance: 0.35, quantity: 2 },
      { itemType: "currency", itemName: "Gold", chance: 1.0, quantity: 4000 },
    ],
    xpReward: 14000,
    goldReward: 4000,
    isWorldBoss: false,
    isAbyssBoss: false,
    isEnabled: true,
  },
  {
    name: "Roswaal L Mathers",
    title: "The Margrave of Magic",
    animeSource: "Re:Zero",
    element1: "Fire" as const,
    element2: "Ice" as const,
    tier: "elite",
    hp: 28000,
    atk: 750,
    def: 450,
    spd: 190,
    crit: 0.20,
    critDmg: 2.0,
    phases: [
      { threshold: 0.40, name: "Full Power Mana Burst", atkMultiplier: 1.8, defMultiplier: 1.2, spdMultiplier: 1.3, mechanic: "Unleashes all elemental magic simultaneously", specialMove: { name: "All Element Barrage", description: "Fires every element at once in a devastating combination", damage: 2.4, effect: "all_element" } },
    ],
    weaknesses: ["Dark", "Order"],
    resistances: ["Fire", "Ice", "Wind"],
    immunities: [],
    skills: [
      { name: "Jiwald", description: "Shoots a heat ray with pinpoint accuracy", damage: 1.6, energyCost: 20, cooldown: 2 },
      { name: "Shamak", description: "Erases the enemy's senses", damage: 1.2, energyCost: 25, cooldown: 2, effect: "blind" },
    ],
    passive: "Book of Wisdom: Knows all player abilities in advance",
    lootTable: [
      { itemType: "material", itemName: "Mana Crystal", chance: 0.4, quantity: 2 },
      { itemType: "currency", itemName: "Gold", chance: 1.0, quantity: 3200 },
    ],
    xpReward: 10000,
    goldReward: 3200,
    isWorldBoss: false,
    isAbyssBoss: false,
    isEnabled: true,
  },
  // ─── MORE WORLD BOSSES ──────────────────────────────────────────────────────
  {
    name: "Monkey D. Dragon",
    title: "The Most Wanted Man in the World",
    animeSource: "One Piece",
    element1: "Wind" as const,
    element2: "Lightning" as const,
    tier: "world",
    hp: 480000,
    atk: 3600,
    def: 2100,
    spd: 310,
    crit: 0.28,
    critDmg: 2.6,
    phases: [
      { threshold: 0.70, name: "Revolutionary Storm", atkMultiplier: 1.3, defMultiplier: 1.1, spdMultiplier: 1.2, mechanic: "Calls a revolutionary storm to debuff all enemies", specialMove: { name: "World-Ending Tempest", description: "An unstoppable revolutionary storm covers the battlefield", damage: 1.8, effect: "all_debuff" } },
      { threshold: 0.35, name: "Dragon's Roar", atkMultiplier: 1.8, defMultiplier: 1.5, spdMultiplier: 1.4, mechanic: "Storm intensifies — deals damage every round", specialMove: { name: "Continental Cyclone", description: "Summons a continental-scale wind that crushes everything", damage: 2.8 } },
    ],
    weaknesses: ["Dark", "Earth"],
    resistances: ["Wind", "Lightning"],
    immunities: [],
    skills: [
      { name: "Gale Slash", description: "Cuts through enemies with compressed wind", damage: 1.6, energyCost: 20, cooldown: 1 },
      { name: "Storm Wall", description: "A wall of wind that absorbs incoming attacks", damage: 1.0, energyCost: 30, cooldown: 3, effect: "shield" },
      { name: "Dragon's Wrath", description: "Channels the full fury of the revolution", damage: 2.4, energyCost: 55, cooldown: 4 },
    ],
    passive: "Revolutionary Will: Reduces all damage taken by 15%",
    lootTable: [
      { itemType: "summon_ticket", itemName: "Dragon's Mark Ticket", chance: 0.04, quantity: 1 },
      { itemType: "material", itemName: "Revolutionary Banner", chance: 0.3, quantity: 2 },
      { itemType: "currency", itemName: "Gold", chance: 1.0, quantity: 5200 },
    ],
    xpReward: 52000,
    goldReward: 10500,
    isWorldBoss: true,
    isAbyssBoss: false,
    isEnabled: true,
  },
  {
    name: "Esdeath",
    title: "The Empire's Strongest General",
    animeSource: "Akame ga Kill",
    element1: "Ice" as const,
    element2: "Dark" as const,
    tier: "world",
    hp: 520000,
    atk: 3700,
    def: 2000,
    spd: 290,
    crit: 0.32,
    critDmg: 2.7,
    phases: [
      { threshold: 0.65, name: "Makahadoma — Ice Palace", atkMultiplier: 1.4, defMultiplier: 1.3, spdMultiplier: 1.0, mechanic: "All enemies slowed 50% by frozen domain", specialMove: { name: "Makahadoma", description: "Freezes all enemies in a domain of absolute ice", damage: 1.9, effect: "mass_freeze" } },
      { threshold: 0.30, name: "Temporal Manipulation — Stopped World", atkMultiplier: 2.0, defMultiplier: 1.8, spdMultiplier: 0.5, mechanic: "Time stops for all but Esdeath", specialMove: { name: "Time Stop", description: "Stops time and attacks freely for 2 rounds", damage: 3.0, effect: "time_stop" } },
    ],
    weaknesses: ["Fire", "Light"],
    resistances: ["Ice", "Dark"],
    immunities: ["Ice"],
    skills: [
      { name: "Weiss Schnabel", description: "Fires 16 lances of ice in all directions", damage: 2.0, energyCost: 30, cooldown: 2 },
      { name: "Grauhorn", description: "Summons an enormous ice horn from below", damage: 1.8, energyCost: 25, cooldown: 2 },
      { name: "Hagelsprung", description: "Drops a massive ice ball from the sky", damage: 2.5, energyCost: 50, cooldown: 4 },
    ],
    passive: "The Strongest: Ignores 20% of all defenses",
    lootTable: [
      { itemType: "summon_ticket", itemName: "General's Teigu Ticket", chance: 0.04, quantity: 1 },
      { itemType: "material", itemName: "Demon's Extract Crystal", chance: 0.3, quantity: 3 },
      { itemType: "currency", itemName: "Gold", chance: 1.0, quantity: 5700 },
    ],
    xpReward: 57000,
    goldReward: 11500,
    isWorldBoss: true,
    isAbyssBoss: false,
    isEnabled: true,
  },
  {
    name: "Whitebeard (Prime)",
    title: "The Strongest Man in the World",
    animeSource: "One Piece",
    element1: "Earth" as const,
    element2: "Water" as const,
    tier: "world",
    hp: 650000,
    atk: 4300,
    def: 2400,
    spd: 240,
    crit: 0.27,
    critDmg: 2.5,
    phases: [
      { threshold: 0.60, name: "Gura Gura Tremor Quake", atkMultiplier: 1.4, defMultiplier: 1.2, spdMultiplier: 1.0, mechanic: "All attacks cause earthquake aftershocks", specialMove: { name: "Quake Fist", description: "Cracks the air itself with a single punch", damage: 2.2, effect: "stun" } },
      { threshold: 0.25, name: "Final Stand — Dying Will", atkMultiplier: 2.3, defMultiplier: 0.8, spdMultiplier: 1.2, mechanic: "Goes berserk — attacks twice but takes 20% more damage", specialMove: { name: "World Shaker", description: "Creates a tsunami with a single shockwave", damage: 3.5 } },
    ],
    weaknesses: ["Lightning", "Wind"],
    resistances: ["Earth", "Water"],
    immunities: [],
    skills: [
      { name: "Gura Gura no Mi", description: "Creates seismic shockwaves through any surface", damage: 2.0, energyCost: 25, cooldown: 2 },
      { name: "Naginata Slash", description: "A devastating bisento slash empowered by quake power", damage: 2.2, energyCost: 30, cooldown: 2 },
      { name: "Fleet Tsunami", description: "Tilts the sea to create a massive tsunami", damage: 2.8, energyCost: 55, cooldown: 5 },
    ],
    passive: "Strongest Man: Immune to the first 5 attacks per battle",
    lootTable: [
      { itemType: "summon_ticket", itemName: "Yonko Commander Ticket", chance: 0.05, quantity: 1 },
      { itemType: "material", itemName: "Vivre Card Fragment", chance: 0.35, quantity: 3 },
      { itemType: "currency", itemName: "Gold", chance: 1.0, quantity: 6500 },
    ],
    xpReward: 65000,
    goldReward: 13000,
    isWorldBoss: true,
    isAbyssBoss: false,
    isEnabled: true,
  },
  {
    name: "Meliodas (Demon King Vessel)",
    title: "Captain of the Seven Deadly Sins",
    animeSource: "Seven Deadly Sins",
    element1: "Dark" as const,
    element2: "Chaos" as const,
    tier: "world",
    hp: 580000,
    atk: 3900,
    def: 2100,
    spd: 330,
    crit: 0.35,
    critDmg: 2.8,
    phases: [
      { threshold: 0.65, name: "Full Counter Aura", atkMultiplier: 1.4, defMultiplier: 1.2, spdMultiplier: 1.1, mechanic: "Full Counter reflects all magic attacks", specialMove: { name: "Revenge Counter", description: "Absorbs all damage to release it in one devastating counterattack", damage: 2.5, effect: "damage_reflect_stored" } },
      { threshold: 0.30, name: "Demon King's Power", atkMultiplier: 2.0, defMultiplier: 1.8, spdMultiplier: 1.5, mechanic: "Power of the Demon King makes all strikes unavoidable", specialMove: { name: "Black Haze of Calamity", description: "The Demon King's dark power corrupts everything it touches", damage: 3.8, effect: "curse_all" } },
    ],
    weaknesses: ["Light", "Order"],
    resistances: ["Dark", "Chaos", "Fire"],
    immunities: [],
    skills: [
      { name: "Full Counter", description: "Reflects all magic attacks at double power", damage: 2.0, energyCost: 10, cooldown: 2, effect: "reflect" },
      { name: "Hell Blaze", description: "Dark flames that cannot be extinguished", damage: 2.1, energyCost: 30, cooldown: 2 },
      { name: "Cruel Sun", description: "Creates a miniature dark sun", damage: 2.8, energyCost: 55, cooldown: 5 },
    ],
    passive: "Commandment of Love: Any who feel hatred take damage each round",
    lootTable: [
      { itemType: "summon_ticket", itemName: "Dragon Sin Ticket", chance: 0.04, quantity: 1 },
      { itemType: "material", itemName: "Demon King's Shard", chance: 0.25, quantity: 2 },
      { itemType: "currency", itemName: "Gold", chance: 1.0, quantity: 5900 },
    ],
    xpReward: 59000,
    goldReward: 11800,
    isWorldBoss: true,
    isAbyssBoss: false,
    isEnabled: true,
  },
  // ─── MORE ABYSS FLOORS ──────────────────────────────────────────────────────
  {
    name: "Orochimaru (White Snake Sage)",
    title: "The Legendary Sannin",
    animeSource: "Naruto",
    element1: "Dark" as const,
    element2: "Wind" as const,
    tier: "abyss",
    hp: 11000,
    atk: 460,
    def: 290,
    spd: 170,
    crit: 0.15,
    critDmg: 1.85,
    phases: [
      { threshold: 0.50, name: "White Snake Form", atkMultiplier: 1.5, defMultiplier: 1.2, spdMultiplier: 1.3, mechanic: "Slithers to avoid attacks, gains evasion", specialMove: { name: "Thousand Snakes Technique", description: "Releases a flood of deadly snakes on the target", damage: 2.0, effect: "poison_aoe" } },
    ],
    weaknesses: ["Fire", "Lightning"],
    resistances: ["Dark", "Wind", "Earth"],
    immunities: [],
    skills: [
      { name: "Eight Branches Jutsu", description: "Transforms into an eight-headed snake beast", damage: 1.8, energyCost: 35, cooldown: 3 },
      { name: "Kusanagi Sword", description: "Extends a blade that can pierce anything", damage: 1.5, energyCost: 20, cooldown: 2 },
    ],
    passive: "Immortal Research: Heals 2% HP per round",
    lootTable: [
      { itemType: "material", itemName: "Snake Scale", chance: 0.6, quantity: 2 },
      { itemType: "currency", itemName: "Gold", chance: 1.0, quantity: 800 },
    ],
    xpReward: 2500,
    goldReward: 800,
    isWorldBoss: false,
    isAbyssBoss: true,
    abyssFloor: 15,
    isEnabled: true,
  },
  {
    name: "Hisoka Morow",
    title: "The Magician — Treacherous Hunter",
    animeSource: "Hunter x Hunter",
    element1: "Wind" as const,
    element2: "Dark" as const,
    tier: "abyss",
    hp: 25000,
    atk: 700,
    def: 400,
    spd: 230,
    crit: 0.25,
    critDmg: 2.1,
    phases: [
      { threshold: 0.45, name: "Bungee Gum Revealed", atkMultiplier: 1.6, defMultiplier: 1.2, spdMultiplier: 1.4, mechanic: "Bungee Gum reattaches and counters every deflected hit", specialMove: { name: "Bungee Gum Barrage", description: "Fires a rapid volley of Bungee Gum strikes", damage: 2.3, effect: "multi_hit" } },
    ],
    weaknesses: ["Lightning", "Order"],
    resistances: ["Wind", "Dark"],
    immunities: [],
    skills: [
      { name: "Texture Surprise", description: "Disguises as an ally to strike from behind", damage: 1.5, energyCost: 20, cooldown: 2, effect: "sneak" },
      { name: "Bungee Gum", description: "Elastic Nen that stretches and rebounds strikes", damage: 1.8, energyCost: 25, cooldown: 2 },
    ],
    passive: "Bloodlust: Gains 8% ATK each time it lands a crit",
    lootTable: [
      { itemType: "material", itemName: "Trick Card", chance: 0.5, quantity: 1 },
      { itemType: "currency", itemName: "Gold", chance: 1.0, quantity: 2000 },
    ],
    xpReward: 5500,
    goldReward: 2000,
    isWorldBoss: false,
    isAbyssBoss: true,
    abyssFloor: 25,
    isEnabled: true,
  },
  {
    name: "Gojo Satoru (Sealed)",
    title: "The World's Strongest Jujutsu Sorcerer",
    animeSource: "Jujutsu Kaisen",
    element1: "Light" as const,
    element2: "Space" as const,
    tier: "abyss",
    hp: 55000,
    atk: 1100,
    def: 700,
    spd: 270,
    crit: 0.28,
    critDmg: 2.3,
    phases: [
      { threshold: 0.40, name: "Limitless Unleashed", atkMultiplier: 1.8, defMultiplier: 1.6, spdMultiplier: 1.5, mechanic: "Infinity renders all direct attacks useless — must use AoE", specialMove: { name: "Hollow Purple", description: "Combines Blue and Red to create an erase technique", damage: 3.2, effect: "existence_erase" } },
    ],
    weaknesses: ["Dark", "Chaos"],
    resistances: ["Light", "Space"],
    immunities: ["Direct attacks while Infinity is active"],
    skills: [
      { name: "Infinity — Cursed Technique", description: "Slows all projectiles to near-zero speed", damage: 0.0, energyCost: 0, cooldown: 0, effect: "passive_immunity" },
      { name: "Red — Reversal", description: "Forces repulsion on the target", damage: 1.8, energyCost: 25, cooldown: 2 },
      { name: "Blue — Attraction", description: "Collapses space around the target", damage: 2.0, energyCost: 30, cooldown: 2 },
    ],
    passive: "Six Eyes: Sees all enemy actions one step ahead",
    lootTable: [
      { itemType: "material", itemName: "Six Eyes Fragment", chance: 0.25, quantity: 1 },
      { itemType: "currency", itemName: "Gold", chance: 1.0, quantity: 4000 },
    ],
    xpReward: 12000,
    goldReward: 4000,
    isWorldBoss: false,
    isAbyssBoss: true,
    abyssFloor: 35,
    isEnabled: true,
  },
  {
    name: "Sinbad (Sin Form)",
    title: "The King of Sindria — Seven Dungeon Conqueror",
    animeSource: "Magi",
    element1: "Lightning" as const,
    element2: "Wind" as const,
    tier: "abyss",
    hp: 110000,
    atk: 1700,
    def: 1000,
    spd: 280,
    crit: 0.27,
    critDmg: 2.2,
    phases: [
      { threshold: 0.45, name: "All Seven Djinn Equip", atkMultiplier: 1.7, defMultiplier: 1.5, spdMultiplier: 1.3, mechanic: "Switches between 7 different elemental forms", specialMove: { name: "Complete Body Djinn Equip", description: "Fully equips all 7 Djinn simultaneously for an overwhelmingly powerful combo", damage: 3.0, effect: "all_element_combo" } },
    ],
    weaknesses: ["Dark", "Earth"],
    resistances: ["Lightning", "Wind", "Water", "Fire"],
    immunities: [],
    skills: [
      { name: "Bararaq Saiqa", description: "A lightning sword technique of supreme power", damage: 2.0, energyCost: 30, cooldown: 2 },
      { name: "Valefor's Ice Djinn", description: "Freezes the battlefield with ice djinn power", damage: 1.8, energyCost: 25, cooldown: 2, effect: "freeze" },
    ],
    passive: "King's Fate: Destiny always bends toward his victory",
    lootTable: [
      { itemType: "material", itemName: "Metal Vessel Fragment", chance: 0.28, quantity: 1 },
      { itemType: "currency", itemName: "Gold", chance: 1.0, quantity: 6000 },
    ],
    xpReward: 20000,
    goldReward: 6000,
    isWorldBoss: false,
    isAbyssBoss: true,
    abyssFloor: 45,
    isEnabled: true,
  },
  {
    name: "Shiki (One Piece)",
    title: "The Flying Pirate — Golden Lion",
    animeSource: "One Piece",
    element1: "Wind" as const,
    element2: "Earth" as const,
    tier: "abyss",
    hp: 190000,
    atk: 2300,
    def: 1400,
    spd: 270,
    crit: 0.27,
    critDmg: 2.3,
    phases: [
      { threshold: 0.45, name: "Fuwa Fuwa Levitation Full Power", atkMultiplier: 1.6, defMultiplier: 1.4, spdMultiplier: 1.3, mechanic: "Lifts entire islands to drop on enemies", specialMove: { name: "Island Drop", description: "Lifts a floating island and drops it on enemies", damage: 2.8, effect: "gravity_crush" } },
    ],
    weaknesses: ["Lightning", "Water"],
    resistances: ["Wind", "Earth"],
    immunities: [],
    skills: [
      { name: "Fuwa Fuwa Slashes", description: "Floats and attacks from every direction", damage: 1.8, energyCost: 25, cooldown: 2 },
      { name: "Gale Sword", description: "Channels wind into devastating sword slashes", damage: 2.0, energyCost: 30, cooldown: 2 },
    ],
    passive: "Flying Lion: Cannot be hit by ground-based attacks",
    lootTable: [
      { itemType: "material", itemName: "Golden Lion Mane", chance: 0.25, quantity: 1 },
      { itemType: "currency", itemName: "Gold", chance: 1.0, quantity: 9000 },
    ],
    xpReward: 30000,
    goldReward: 9000,
    isWorldBoss: false,
    isAbyssBoss: true,
    abyssFloor: 55,
    isEnabled: true,
  },
  {
    name: "Diablo (Demon Lord)",
    title: "Lord of Calamity",
    animeSource: "Tensura",
    element1: "Dark" as const,
    element2: "Chaos" as const,
    tier: "abyss",
    hp: 280000,
    atk: 3000,
    def: 1800,
    spd: 300,
    crit: 0.32,
    critDmg: 2.6,
    phases: [
      { threshold: 0.40, name: "Lord of Calamity Awakens", atkMultiplier: 1.9, defMultiplier: 1.7, spdMultiplier: 1.4, mechanic: "Exerts overwhelming pressure — all enemies take 10% less action", specialMove: { name: "Catastrophe", description: "A wave of calamitous energy that warps reality around it", damage: 3.2, effect: "reality_warp" } },
    ],
    weaknesses: ["Light", "Order"],
    resistances: ["Dark", "Chaos", "Fire"],
    immunities: [],
    skills: [
      { name: "Dark Flame", description: "Unholy flames that burn the soul directly", damage: 2.0, energyCost: 25, cooldown: 2 },
      { name: "Demon Lord's Authority", description: "Commands lesser beings to stop fighting", damage: 1.5, energyCost: 30, cooldown: 3, effect: "charm" },
    ],
    passive: "Primordial Demon: Resists all status ailments",
    lootTable: [
      { itemType: "material", itemName: "Primordial Shard", chance: 0.2, quantity: 1 },
      { itemType: "currency", itemName: "Gold", chance: 1.0, quantity: 12000 },
    ],
    xpReward: 42000,
    goldReward: 12000,
    isWorldBoss: false,
    isAbyssBoss: true,
    abyssFloor: 65,
    isEnabled: true,
  },
  {
    name: "Crocodile (True Form)",
    title: "The Desert King — Shichibukai",
    animeSource: "One Piece",
    element1: "Earth" as const,
    element2: "Wind" as const,
    tier: "abyss",
    hp: 380000,
    atk: 3500,
    def: 2000,
    spd: 260,
    crit: 0.30,
    critDmg: 2.6,
    phases: [
      { threshold: 0.50, name: "Desert Spada Unleashed", atkMultiplier: 1.5, defMultiplier: 1.3, spdMultiplier: 1.2, mechanic: "Each attack steals moisture from the target", specialMove: { name: "Desert Encierro", description: "Turns the target to sand and scatters them", damage: 2.8, effect: "disintegrate" } },
      { threshold: 0.25, name: "Ground Death", atkMultiplier: 2.0, defMultiplier: 1.5, spdMultiplier: 1.0, mechanic: "The ground around him becomes deadly quicksand", specialMove: { name: "Ground Secco", description: "Desiccates everything within 100 meters", damage: 3.5, effect: "area_wither" } },
    ],
    weaknesses: ["Water", "Ice"],
    resistances: ["Earth", "Wind"],
    immunities: ["Physical"],
    skills: [
      { name: "Desert Spada", description: "Creates a massive crescent of sand that slices everything", damage: 2.0, energyCost: 30, cooldown: 2 },
      { name: "Sand Tomb Storm", description: "Engulfs the enemy in a deadly sand storm", damage: 1.7, energyCost: 20, cooldown: 1 },
    ],
    passive: "Logia: Turns into sand when hit by physical strikes",
    lootTable: [
      { itemType: "material", itemName: "Desert King Hook", chance: 0.2, quantity: 1 },
      { itemType: "currency", itemName: "Gold", chance: 1.0, quantity: 16000 },
    ],
    xpReward: 58000,
    goldReward: 16000,
    isWorldBoss: false,
    isAbyssBoss: true,
    abyssFloor: 75,
    isEnabled: true,
  },
  {
    name: "Accelerator (Level 6 Complete)",
    title: "The Absolute Strongest Esper",
    animeSource: "A Certain Magical Index",
    element1: "Chaos" as const,
    element2: "Space" as const,
    tier: "abyss",
    hp: 530000,
    atk: 4000,
    def: 2800,
    spd: 350,
    crit: 0.32,
    critDmg: 2.8,
    phases: [
      { threshold: 0.55, name: "Black Wings — Full Power", atkMultiplier: 1.6, defMultiplier: 1.5, spdMultiplier: 1.4, mechanic: "Wings reflect 50% of all damage", specialMove: { name: "Explosion Pulse", description: "Sends a vector pulse that causes internal explosions", damage: 2.8, effect: "internal_blast" } },
      { threshold: 0.25, name: "Vector Absolute Control", atkMultiplier: 2.2, defMultiplier: 2.0, spdMultiplier: 2.0, mechanic: "Controls all vectors — makes all attacks curve back on attackers", specialMove: { name: "World Eater", description: "Reverses gravity and tears the battlefield apart", damage: 4.0, effect: "gravity_reversal" } },
    ],
    weaknesses: ["Order", "Time"],
    resistances: ["Chaos", "Space", "Wind"],
    immunities: ["All physical"],
    skills: [
      { name: "Atmospheric Control", description: "Commands the atmosphere to attack", damage: 2.2, energyCost: 35, cooldown: 2 },
      { name: "Vector Bomb", description: "Compresses vectors to create a massive explosion", damage: 2.8, energyCost: 55, cooldown: 4 },
    ],
    passive: "God-Tier Redirection: Immune to all attacks below 1000 power",
    lootTable: [
      { itemType: "material", itemName: "Academy City Core", chance: 0.15, quantity: 1 },
      { itemType: "currency", itemName: "Gold", chance: 1.0, quantity: 20000 },
    ],
    xpReward: 82000,
    goldReward: 20000,
    isWorldBoss: false,
    isAbyssBoss: true,
    abyssFloor: 85,
    isEnabled: true,
  },
  {
    name: "Tet (Game God)",
    title: "The One True God of Disboard",
    animeSource: "No Game No Life",
    element1: "Order" as const,
    element2: "Chaos" as const,
    tier: "abyss",
    hp: 800000,
    atk: 6000,
    def: 4000,
    spd: 380,
    crit: 0.40,
    critDmg: 3.5,
    phases: [
      { threshold: 0.60, name: "Absolute Game Rules Invoked", atkMultiplier: 1.6, defMultiplier: 1.8, spdMultiplier: 1.5, mechanic: "All battles become games — must win a mini-game to deal damage", specialMove: { name: "Ten Pledges", description: "Invokes the divine rules that govern all conflict", damage: 2.5, effect: "rule_change" } },
      { threshold: 0.30, name: "True God Form", atkMultiplier: 2.5, defMultiplier: 2.5, spdMultiplier: 2.0, mechanic: "Rewrites reality — random effects occur every round", specialMove: { name: "Reality Rewrite", description: "Changes the rules mid-battle to be impossibly unfair", damage: 5.0, effect: "chaos_rules" } },
    ],
    weaknesses: [],
    resistances: ["Fire", "Water", "Earth", "Wind", "Lightning", "Ice", "Light", "Dark"],
    immunities: ["Time", "Space"],
    skills: [
      { name: "Game Over", description: "Ends the round instantly with a game result", damage: 3.0, energyCost: 40, cooldown: 3, effect: "instant_round_end" },
      { name: "Divine Gambit", description: "Places a bet — double damage or forfeit turn", damage: 4.0, energyCost: 30, cooldown: 2, effect: "gamble" },
    ],
    passive: "Omniscient God: Knows all player strategies; negates first attack every round",
    lootTable: [
      { itemType: "summon_ticket", itemName: "God's Game Piece Ticket", chance: 0.02, quantity: 1 },
      { itemType: "material", itemName: "Disboard Fragment", chance: 0.12, quantity: 1 },
      { itemType: "currency", itemName: "Gold", chance: 1.0, quantity: 35000 },
    ],
    xpReward: 140000,
    goldReward: 35000,
    isWorldBoss: false,
    isAbyssBoss: true,
    abyssFloor: 95,
    isEnabled: true,
  },
  // ─── LEGENDARY BOSS ─────────────────────────────────────────────────────────
  {
    name: "Zeno (Omni-King)",
    title: "The King of All — Destroyer of Universes",
    animeSource: "Dragon Ball Super",
    element1: "Order" as const,
    element2: "Chaos" as const,
    tier: "legendary",
    hp: 1000000,
    atk: 9999,
    def: 5000,
    spd: 400,
    crit: 0.50,
    critDmg: 5.0,
    phases: [
      { threshold: 0.70, name: "Erase Activated", atkMultiplier: 1.5, defMultiplier: 1.5, spdMultiplier: 1.3, mechanic: "Can erase any attack", specialMove: { name: "Erase", description: "Erases the target from existence — instant death attempt", damage: 9.9, effect: "erase" } },
      { threshold: 0.40, name: "Second Zeno Appears", atkMultiplier: 2.0, defMultiplier: 2.0, spdMultiplier: 1.5, mechanic: "Two Zenos attack at once", specialMove: { name: "Final Erase", description: "Twin Zenos combine their power to destroy everything", damage: 99.9, effect: "universe_erase" } },
    ],
    weaknesses: [],
    resistances: ["Fire", "Water", "Earth", "Wind", "Lightning", "Ice", "Light", "Dark"],
    immunities: ["Chaos", "Order", "Space", "Time"],
    skills: [
      { name: "Universal Deletion", description: "Deletes a universe — massive damage to single target", damage: 5.0, energyCost: 50, cooldown: 3 },
      { name: "Childlike Fury", description: "A random but devastating attack", damage: 3.0, energyCost: 20, cooldown: 1 },
    ],
    passive: "Omni-King: Immune to all negative status effects",
    lootTable: [
      { itemType: "summon_ticket", itemName: "Omni-King Ticket", chance: 0.01, quantity: 1 },
      { itemType: "material", itemName: "Universe Shard", chance: 0.1, quantity: 1 },
      { itemType: "currency", itemName: "Gold", chance: 1.0, quantity: 50000 },
    ],
    xpReward: 200000,
    goldReward: 50000,
    isWorldBoss: false,
    isAbyssBoss: true,
    abyssFloor: 100,
    isEnabled: true,
  },
];

async function seed() {
  console.log(`Seeding ${bosses.length} bosses...`);
  let inserted = 0;

  for (const boss of bosses) {
    try {
      await db.insert(bossesTable).values(boss as any).onConflictDoNothing();
      inserted++;
      console.log(`  [${inserted}/${bosses.length}] ${boss.name}`);
    } catch (err) {
      console.error(`  Failed: ${boss.name}:`, err);
    }
  }

  console.log(`\n✅ Done! Seeded ${inserted} bosses.`);
  await pool.end();
}

seed().catch(err => { console.error(err); pool.end(); process.exit(1); });
